#------------------------------------------------------------------------------
# 実行： docker-compose run tf_infra
#        
# 終了：docker-compose down
#------------------------------------------------------------------------------
version: "3.8"
services:
  # Terraform 環境
  tf_lt:
    build:
      context: ./
      dockerfile: Dockerfile
    image: tf_lt
    volumes:
       - "./:/root/work"
       - "$HOME/.aws:/root/.aws"
    working_dir: /root/work

